name: Build and push civi buildkit image

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          # relative path to the place where source code with Dockerfile is located
          context: ./civicrm
          tags: bhawest/cividist-base-2:latest